version: 1.3.1.{build}
pull_requests:
  do_not_increment_build_number: true
os: Windows Server 2012 R2
shallow_clone: true
build_script:
- cd "%APPVEYOR_BUILD_FOLDER%"
- mkdir build-dll
- mkdir build-lib
- mkdir output
- cd build-dll
- cmake -G "Visual Studio 12 2013 Win64" -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%\output" ..
- msbuild INSTALL.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cd ..\build-lib
- cmake -G "Visual Studio 12 2013 Win64" -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%\output" ..
- msbuild INSTALL.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: .\output\
  name: epoxy-vc12-x64
